### ISSUE TITLE
rounded highlighter + bold text, not being styled as bold during Live Preview

### ISSUE THREAD

**Issue by Matt-Sim** [chetachiezikeuzor/Highlightr-Plugin#26]
sample md:
```markdown
not bold (**bold without highlight**) not bold
==not bold (**bold within highlight**) not bold==
not bold (**==highlight within bold==**) not bold
```

rendered result, using Rounded highlighter during Editor Live Preview:
![image](https://user-images.githubusercontent.com/98189551/152347741-77606777-a117-4f0a-82f1-d85921e8ced1.png)

Problem seems to go away if this rule is removed:
```css
.highlightr-rounded .cm-s-obsidian span.cm-highlight {
    font-weight: inherit;
}
```

Also, this type of rule doesn't exist for any of the other highlighter styles, so i assume it isn't needed.

**Comment by looneyapache** [comment]
I had the same issue, But removing recommended rule doesn't seem to help much. Highlighted text cannot be formatted as bold/italic or others

**Comment by Matt-Sim** [comment]
**workaround:**
create a [css snippet](https://help.obsidian.md/How+to/Add+custom+styles#Use+Themes+and+or+CSS+snippets) with this rule
```css
/* fix bold within highlight */
.highlightr-rounded .cm-s-obsidian .cm-highlight.cm-strong {
    font-weight: 800;
}
```
