### ISSUE TITLE
Feature request: Support for coloring text

### ISSUE THREAD

**Issue by kkollsga** [chetachiezikeuzor/Highlightr-Plugin#33]
If possible would be nice to ad a function in the dropdown to color the text. The color options can be the same as the Highlighting colors.

**Comment by PiotrG1996** [comment]
@chetachiezikeuzor 

Please implement this functionality ☺️

> If possible would be nice to ad a function in the dropdown to color the text. The color options can be the same as the Highlighting colors.

**Comment by user216** [comment]
+1

**Comment by OnkelTem** [comment]
+1

I personally prefer text highlights over background ones. I just need to make my bold text of different colors.

**Comment by caasion** [comment]
I have found somewhat of a work-around using a css snippet, it requires some manual work in setting the colors, but it works great.

```css
/* instead of background, change text color for defined highlights(highlights starting with 'hltr-font-')*/
mark[class^="hltr-font-"], mark[class*="hltr-font-"]
{
    background: transparent !important;
    background-color: transparent !important;
}
/* defines colors; colors taken from html color templates */
mark.hltr-font-red { color: #FF0000 !important }
mark.hltr-font-orange { color: #FFA500 !important }
mark.hltr-font-yellow { color: #FFFF00 !important }
mark.hltr-font-green { color: #008000 !important }
mark.hltr-font-limegreen { color: #32CD32 !important }
mark.hltr-font-lime { color: #00FF00 !important }
mark.hltr-font-aqua { color: #00FFFF !important }
mark.hltr-font-blue { color: #0000FF !important }
mark.hltr-font-purple { color: #800080 !important }
mark.hltr-font-violet { color: #EE82EE !important }
mark.hltr-font-pink { color: #FFC0CB !important }
mark.hltr-font-brown { color: #A52A2A !important }
mark.hltr-font-gray { color: #A0A0A0 !important }
mark.hltr-font-white { color: #FFFFFF !important }
mark.hltr-font-black { color: #000000 !important }
```

This requires you to manually change colors you want, but it works along with normal highlights and serves as a good alternative while we wait for the pull request.

To use this, just name your highlight "font-(whatever color)", or name it something else you desire.

I also modified the plugin a little to make it so only colored text highlights have a circle inside, but normal highlights only has a outer circle. 
_Note: the css i sent doesn't change the menu like this_
![image](https://user-images.githubusercontent.com/103465188/172006412-52c9c11d-c1f3-496f-b377-bff1bad22393.png)

This is the code:
```javascript
if (/^font-.*$/gmi.test(highlighter)) {
                colorButtonIcon.innerHTML =
                    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1.15em" height="1.15em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><title>' +
                        highlighter +
                        '</title><path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10s-4.477 10-10 10zm0-2a8 8 0 1 0 0-16a8 8 0 0 0 0 16zm0-3a5 5 0 1 1 0-10a5 5 0 0 1 0 10z""/></svg>';
            } else {
                colorButtonIcon.innerHTML =
                    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1.15em" height="1.15em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><title>' +
                        highlighter +
                        '</title><path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10s-4.477 10-10 10zm0-2a8 8 0 1 0 0-16a8 8 0 0 0 0 16z""/></svg>';
            }
```
and it replaces the part where there is
`if (/^font-.*$/gmi.test(highlighter)) {...}` 
_I don't exactly know where (since I changed it already), so if you don't really know where it is, please avoid doing this_
