### ISSUE TITLE
Feature request: Text Color mode and Minimal menu

### ISSUE THREAD

**Issue by KraXen72** [chetachiezikeuzor/Highlightr-Plugin#61]
This issue is two feature requests, both should be added as a new setting into the plugin.
## minimal menu:
change the highlighter menu to this minimal variant:
![image](https://user-images.githubusercontent.com/21956756/208741403-ad3fa34d-5488-416e-8af3-3717fe8db0ce.png)
  
 ## text color mode
makes it so that highlights don't change text background color, but actual text's color:
![image](https://user-images.githubusercontent.com/21956756/208741566-1547bf6f-0e3b-4034-ada7-fc267305bee9.png)

i have implemented both as a css snippet, feel free to use the code there to implement these features, but please do atleast mention my github username in the changelog if you decide to use my code.

```css
/* data.json for highlightr plugin */
/* replce your highlightr config located in: [vault]\.obsidian\plugins\highlightr-plugin\data.json */
/* {"highlighterStyle":"rounded","highlighterMethods":"css-classes","highlighters":{"r":"#bf616a","g":"#a3be8c","p":"#b48ead","b":"#81a1c1","aa":"#a5756233","o":"#d08770"},"highlighterOrder":["aa","r","g","b","p","o"]} */

/* restyle the vanilla highlight to rosebox color */
.markdown-preview-view,
.cm-s-obsidian span.cm-formatting-highlight, 
.cm-s-obsidian span.cm-highlight  { --text-highlight-bg: #a5756233; }

.theme-dark .markdown-preview-view mark,
.markdown-preview-view mark,
:is(.markdown-preview-view, .markdown-rendered) mark, 
.cm-s-obsidian span.cm-highlight { 
	background: #a5756233; 
	color: var(--text-normal);
}

/* remove border radius from normal highlight */
.highlightr-rounded span.cm-highlight:not(.hltr-aa) {
    border-radius: 0px !important;
}

/* instead of background, change text color for defined highlights */
mark.hltr-r,
mark.hltr-g,
mark.hltr-b,
mark.hltr-p,
mark.hltr-o
{
    background: transparent !important;
    background-color: transparent !important;
    padding-left: 0px !important;
    padding-right: 0px !important;
}
/* taken from nord pallete colors */
mark.hltr-r { color: #bf616a !important }
mark.hltr-g { color: #a3be8c !important }
mark.hltr-b { color: #81a1c1 !important }
mark.hltr-p { color: #b48ead !important }
mark.hltr-o { color: #d08770 !important }
mark.hltr-aa { color: var(--text-normal) }

/* highlightr compact menu */
.menu.highlighterContainer {
    display: flex !important;
    width: max-content !important;
    padding: .2rem .5rem !important;
    overflow-x: none !important;
}
.menu.highlighterContainer .menu-item {
   padding: 0;
   margin: 0;
   border-bottom: transparent;
   border-radius: 5px;
   
   justify-content: center;
   align-items: center;

   aspect-ratio: 1/1;

}
.menu.highlighterContainer .menu-item .menu-item-title {
	display: none;
}
.menu.highlighterContainer .menu-item .menu-item-icon {
	height: min-content;
	width: min-content;
}

/* consistent icon stroke width with others */
.highlightr-eraser svg path, .highlightr-pen svg path {
    stroke-width: .3px !important;
}
```
